[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "Pixelify Sans"
url = "app/static/PixelifySans-Regular.ttf"
style="normal"

[theme]
base = "dark"
primaryColor = "#b7d1ea"
backgroundColor = "#34292a"
secondaryBackgroundColor = "#51342c"
textColor = "#efebc4"
linkColor = "#dabf5c"
showWidgetBorder = false
font="Pixelify Sans"