[server]
enableStaticServing = true

[[theme.fontFaces]]
family="Pixelify Sans"
url="https://fonts.googleapis.com/css2?family=Pixelify+Sans:wght@400..700&display=swap"

[theme]
base = "dark"
primaryColor = "#b7d1ea"
backgroundColor = "#34292a"
secondaryBackgroundColor = "#51342c"
textColor = "#efebc4"
linkColor = "#dabf5c"
showWidgetBorder = false
